version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: mc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: mc_platform
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mc_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
